version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_docker
    environment:
      POSTGRESQL_USERNAME: docker_postgres
      POSTGRESQL_PASSWORD: docker_root123
      POSTGRES_DATABASE: docker_users
    ports:
      - "5432:5432"
  java-spring-app:
    image: spring-app:latest
    build: .
    container_name: java-spring-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"


